### ISSUE TITLE
Epic m4ag-firmware Documentation Review

### ISSUE THREAD

**Issue by eduazocar** [Mesh4all/m4ag-firmware#22]
It's necessary to correctly maintain the documentation structure of the repository.
This adds more aesthetics to the repository that we are working.

- [x] README review
- [x] CODING_CONVENTION.md
- [x] CONTRIBUTING.md
- [x] CONTRIBUTORS
- [x] CODE_OF_CONDUCT.md
- [ ] Repository Labels Review

**Comment by eduazocar** [comment]
it's necessary to add all labels to this repository
